version: '3.8'

services:
  nodered:
    image: nodered/node-red:latest
    container_name: aquajardim_nodered
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: aquajardim_influx
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped

volumes:
  nodered_data:
  influxdb_data: